version: '3'

services:
  web:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./backend:/app
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql/
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
  front:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '8080:8080'
    environment:
      API_URL: http://localhost:3000
    tty: true
    stdin_open: true
    command: npm run serve

volumes:
  mysql_data:
    driver: local