version: '3'

services:
  # 開発環境用
  # front:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.build
  #   command: npm run serve
  #   ports:
  #     - '8080:8080'
  #   volumes:
  #     - ./frontend:/app
  #   environment:
  #     VUE_APP_API_HOST: http://localhost:3000
  #   tty: true
  #   stdin_open: true
  # 本番環境用
  front:
    build: ./frontend
    ports:
      - '8080:80'
    tty: true
    stdin_open: true
  nginx:
    build: ./nginx
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    environment:
      DB_HOST: db
      FRONTEND_HOST: http://localhost:8080
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql/
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'

volumes:
  public-data:
  tmp-data:
  log-data:
  mysql_data:
    driver: local
