version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.2-node
    working_directory: ~/project/backend
    steps:
      - checkout
      - run:
          name: "bundle install"
          command: "backend/bin/bundle install"
      - run:
          name: "waiting DB start"
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: "initialize DB"
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate

workflows:
  version: 2
  build:
    jobs:
      - build
