version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.2-node
      - image: circleci/mysql8.0
        name: "db"
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: password
    working_directory: ~/project/backend
    steps:
      - checkout
      - ruby/install-deps

workflows:
  version: 2
  build:
    jobs:
      - build
