version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.2-node
    working_directory: ~/project/backend
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: yarn.lock

workflows:
  version: 2
  build:
    jobs:
      - build
