version: 2.1

orbs:
  cypress: cypress-io/cypress@1

executors:
  api:
    working_directory: ~/project
    docker:
      - image: circleci/ruby:3.0.2-node
        environment:
          - BUNDLER_VERSION: 2.2.22
          - RAILS_ENV: test
          - DB_HOST: 127.0.0.1
      - image: circleci/mysql:8.0
        environment:
          - MYSQL_ROOT_HOST: '%'
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
  front:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.18.3

commands:
  backend_setup:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./backend/Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: backend install dependencies
          command: |
            cd ./backend
            gem install bundler -v 2.2.22
            bundle install --jobs=4 --retry=3
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "./backend/Gemfile.lock" }}
  db_setup:
    steps:
      - run:
          name: Use specific database.yml
          command: mv ./backend/config/database.yml.ci ./backend/config/database.yml
      - run:
          name: database setup
          command: |
            cd ./backend
            rails db:create
            rails db:migrate
  frontend_setup:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./frontend/yarn.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            cd ./frontend
            yarn install
      - run:
          name: build
          command: |
            cd ./frontend
            yarn build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "./frontend/yarn.lock" }}
  eslint:
    steps:
      - run:
          name: eslint
          command: |
            cd ./frontend
            yarn lint
  unit_test:
    steps:
      - run:
          name: jest
          environment:
            NODE_OPTIONS: --max_old_space_size=4096
          command: |
            cd ./frontend
            yarn test:unit

jobs:
  api_build:
    executor: api
    environment:
      RAILS_ENV: test
    working_directory: ~/project
    steps:
      - checkout
      - backend_setup
  rubocop:
    executor: api
    environment:
      RAILS_ENV: test
    working_directory: ~/project
    steps:
      - checkout
      - backend_setup
      - db_setup
      - run:
          name: rubocop
          command: |
            cd ./backend
            bundle exec rubocop
  rspec:
    executor: api
    environment:
      RAILS_ENV: test
    working_directory: ~/project
    steps:
      - checkout
      - backend_setup
      - db_setup
      - run:
          name: rspec
          command: |
            cd ./backend
            bin/rspec
  front_build:
    executor: front
    working_directory: ~/project
    steps:
      - checkout
      - frontend_setup
  eslint:
    executor: front
    working_directory: ~/project
    steps:
      - checkout
      - frontend_setup
      - eslint
  unit_test:
    executor: front
    working_directory: ~/project
    steps:
      - checkout
      - frontend_setup
      - unit_test

workflows:
  version: 2
  api:
    jobs:
      - api_build
      - rspec:
          requires:
            - api_build
      - rubocop:
          requires:
            - api_build
  front:
    jobs:
      - front_build
      - eslint:
          requires:
            - front_build
      - unit_test:
          requires:
            - front_build
      - cypress/run:
          cache-key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "./frontend/package.json" }}
          working_directory: ~/project/frontend
          yarn: true
          command: yarn test:e2e --headless